name: paralogSL
channels:
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - scikit-learn=0.23.1
  - seaborn=0.9.0
  - pandas=1.0.1
  - statsmodels=0.11.0
  - biopython
  - scipy=1.4.1
  - numpy=1.18.5
  - ipykernel
  - requests
  - matplotlib-venn
  - xlrd
  - altair
  - matplotlib=3.3.2
  - shap=0.35.0
variables:
  3rd_party_dir: G:/My Drive/3rd_party_data
